### ISSUE TITLE
bower install not working

### ISSUE THREAD

**Issue by omar16100** [GoogleCloudPlatform/solutions-vision-search#1]
$ bower install
bower ENOENT        No bower.json present

**Comment by wwoo** [comment]
Please ensure you have copied all the files from the
third_party/polymer_stater directory (which is where bower.json is located)
in the previous step:

cp -rv solutions-vision-search/third_party/polymer-starter/.
solutions-vision-search/gae/frontend

Then follow up with:

cd solutions-vision-search/gae/frontend
bower install

**Comment by omar16100** [comment]
It works now, thank you!
